### ISSUE TITLE
enable linux/arm/v6 support

### ISSUE THREAD

**Issue by tristan-k** [dubo-dubon-duponey/docker-shairport-sync#11]
Can you enable support for linux/arm/v6 by default. I'm trying to run your docker image on a raspberry zero w.

**Comment by dubo-dubon-duponey** [comment]
Hey, missed that message, sorry. I'll enable it.

**Comment by dubo-dubon-duponey** [comment]
Done. `docker buildx imagetools inspect ghcr.io/dubo-dubon-duponey/airplay` <- arm6, arm7, arm64, amd64
